"""
Encrypt / decrypt helpers for SIP secrets stored in location_sip_config.

The SIP register password (customer PBX side) and the SIP Client password
(softphone side, generated by us) are both stored as pgcrypto-encrypted
BYTEA columns:
    - jambonz_client_password_encrypted
    - sip_register_password_encrypted

The passphrase comes from env var SIP_SECRETS_PASSPHRASE. It must match
across every service that decrypts (today: celery + speako-agent-admin).
"""

import os
import secrets


def get_passphrase() -> str:
    pw = os.getenv("SIP_SECRETS_PASSPHRASE")
    if not pw:
        raise RuntimeError(
            "SIP_SECRETS_PASSPHRASE env var is not set — required to encrypt/decrypt SIP credentials"
        )
    return pw


def encrypt_sql() -> str:
    """SQL fragment that encrypts a parameter. Use like:

        cur.execute(
            f"UPDATE location_sip_config SET "
            f"jambonz_client_password_encrypted = {encrypt_sql()} "
            f"WHERE location_id = %s",
            (plaintext_password, passphrase, location_id),
        )

    Returns 'pgp_sym_encrypt(%s, %s)' so the caller binds (plaintext, passphrase).
    """
    return "pgp_sym_encrypt(%s, %s)"


def decrypt_sql(column: str) -> str:
    """SQL fragment to decrypt a column into text. Use like:

        cur.execute(
            f"SELECT {decrypt_sql('jambonz_client_password_encrypted')} "
            f"FROM location_sip_config WHERE location_id = %s",
            (passphrase, location_id),
        )
    """
    return f"pgp_sym_decrypt({column}::bytea, %s)"


def generate_password(length_bytes: int = 16) -> str:
    """Generate a strong SIP password (URL-safe, ~22 chars for 16 bytes)."""
    return secrets.token_urlsafe(length_bytes)
